name: Build and Deploy to Azure Web App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Choose a runner with the appropriate OS

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'  # Set your .NET version here

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BileshwarOilMill'  # Set your app name here
        #slot-name: 'production'  # If you have a deployment slot, set it here
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp
